package com.xungengbang.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xungengbang.Bean.ReUploadBean;
import com.xungengbang.Bean.ReUploadComplexBean;
import com.xungengbang.Bean.User;

import com.xungengbang.greendao.ReUploadBeanDao;
import com.xungengbang.greendao.ReUploadComplexBeanDao;
import com.xungengbang.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig reUploadBeanDaoConfig;
    private final DaoConfig reUploadComplexBeanDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ReUploadBeanDao reUploadBeanDao;
    private final ReUploadComplexBeanDao reUploadComplexBeanDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        reUploadBeanDaoConfig = daoConfigMap.get(ReUploadBeanDao.class).clone();
        reUploadBeanDaoConfig.initIdentityScope(type);

        reUploadComplexBeanDaoConfig = daoConfigMap.get(ReUploadComplexBeanDao.class).clone();
        reUploadComplexBeanDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        reUploadBeanDao = new ReUploadBeanDao(reUploadBeanDaoConfig, this);
        reUploadComplexBeanDao = new ReUploadComplexBeanDao(reUploadComplexBeanDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(ReUploadBean.class, reUploadBeanDao);
        registerDao(ReUploadComplexBean.class, reUploadComplexBeanDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        reUploadBeanDaoConfig.clearIdentityScope();
        reUploadComplexBeanDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public ReUploadBeanDao getReUploadBeanDao() {
        return reUploadBeanDao;
    }

    public ReUploadComplexBeanDao getReUploadComplexBeanDao() {
        return reUploadComplexBeanDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
