package com.xungengbang.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.xungengbang.Bean.ReUploadComplexBean.ListConverter;
import java.util.List;

import com.xungengbang.Bean.ReUploadComplexBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RE_UPLOAD_COMPLEX_BEAN".
*/
public class ReUploadComplexBeanDao extends AbstractDao<ReUploadComplexBean, Long> {

    public static final String TABLENAME = "RE_UPLOAD_COMPLEX_BEAN";

    /**
     * Properties of entity ReUploadComplexBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Method = new Property(1, String.class, "Method", false, "METHOD");
        public final static Property Content = new Property(2, String.class, "content", false, "CONTENT");
        public final static Property Bmpcount = new Property(3, int.class, "bmpcount", false, "BMPCOUNT");
        public final static Property FjUrls = new Property(4, String.class, "fjUrls", false, "FJ_URLS");
        public final static Property BmpFileNames = new Property(5, String.class, "bmpFileNames", false, "BMP_FILE_NAMES");
    }

    private final ListConverter fjUrlsConverter = new ListConverter();
    private final ListConverter bmpFileNamesConverter = new ListConverter();

    public ReUploadComplexBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ReUploadComplexBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RE_UPLOAD_COMPLEX_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"METHOD\" TEXT," + // 1: Method
                "\"CONTENT\" TEXT," + // 2: content
                "\"BMPCOUNT\" INTEGER NOT NULL ," + // 3: bmpcount
                "\"FJ_URLS\" TEXT," + // 4: fjUrls
                "\"BMP_FILE_NAMES\" TEXT);"); // 5: bmpFileNames
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RE_UPLOAD_COMPLEX_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ReUploadComplexBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String Method = entity.getMethod();
        if (Method != null) {
            stmt.bindString(2, Method);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
        stmt.bindLong(4, entity.getBmpcount());
 
        List fjUrls = entity.getFjUrls();
        if (fjUrls != null) {
            stmt.bindString(5, fjUrlsConverter.convertToDatabaseValue(fjUrls));
        }
 
        List bmpFileNames = entity.getBmpFileNames();
        if (bmpFileNames != null) {
            stmt.bindString(6, bmpFileNamesConverter.convertToDatabaseValue(bmpFileNames));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ReUploadComplexBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String Method = entity.getMethod();
        if (Method != null) {
            stmt.bindString(2, Method);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
        stmt.bindLong(4, entity.getBmpcount());
 
        List fjUrls = entity.getFjUrls();
        if (fjUrls != null) {
            stmt.bindString(5, fjUrlsConverter.convertToDatabaseValue(fjUrls));
        }
 
        List bmpFileNames = entity.getBmpFileNames();
        if (bmpFileNames != null) {
            stmt.bindString(6, bmpFileNamesConverter.convertToDatabaseValue(bmpFileNames));
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ReUploadComplexBean readEntity(Cursor cursor, int offset) {
        ReUploadComplexBean entity = new ReUploadComplexBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // Method
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // content
            cursor.getInt(offset + 3), // bmpcount
            cursor.isNull(offset + 4) ? null : fjUrlsConverter.convertToEntityProperty(cursor.getString(offset + 4)), // fjUrls
            cursor.isNull(offset + 5) ? null : bmpFileNamesConverter.convertToEntityProperty(cursor.getString(offset + 5)) // bmpFileNames
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ReUploadComplexBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMethod(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setContent(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBmpcount(cursor.getInt(offset + 3));
        entity.setFjUrls(cursor.isNull(offset + 4) ? null : fjUrlsConverter.convertToEntityProperty(cursor.getString(offset + 4)));
        entity.setBmpFileNames(cursor.isNull(offset + 5) ? null : bmpFileNamesConverter.convertToEntityProperty(cursor.getString(offset + 5)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ReUploadComplexBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ReUploadComplexBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ReUploadComplexBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
